//
//  Story.swift
//  Autumn's Song
//
//  Created by Eder Rengifo on 2/02/15.
//  Copyright (c) 2015 Eder Rengifo. All rights reserved.
//

import Foundation

let dictionary = [
    "Crow started his journey with joy.",
    "He leaves his nest behind and faces what winter may bring.",
    "Autumn is almost over, but he has a special mission;",
    "the last flight of his life...",
    
    "- Chapter 1: Flying away from the nest -",
    
    "At the beginning of the autumn, Crow was quite different.",
    "While his brothers were beautiful white birds,",
    "He was different as he was born black as a crow",
    "Angry because of his destiny, he became more bitter every day",
    "“When winter comes, I will stay here to die”…",
    
    "he thought while everybody talked about the migration south,",
    "for all of them like the autumn season and remarked how beautiful it was,",
    "but he never saw that beauty, but rather only sadness and loneliness",
    "The few times that he left the nest during that time…",
    "…it was to fly far away, searching for a quiet place…",
    
    "…where nobody would disturb him.",
    "One afternoon, while he flew above a forest…",
    "He sensed something quite strange there,",
    "a bird had been caught in some branches.",
    "Although he thought twice about it, he ended up flying back to help.",
    
    "The beautiful wings of a robin were stuck in the branches",
    "With a little of effort, he helped free her.",
    "“Thank you! You saved my life!” – She said happily",
    "“What were you trying to do?” – He responded grumpily",
    "“I saw a beautiful flower inside the branches” – she said",
    
    "He could see it too, pink and full of life, but inaccessible",
    "“Why do you need that?” – He asked",
    "She looked at him with curiosity as nobody had done before",
    "“Are you always so angry? – she asked joking with him",
    "Embarrased, Crow looked down…",
    
    "“It’s just... seems odd to me” – he replied",
    "“I collect flowers” – She explained",
    "“Why?” – Crow asked with curiosity",
    "“I like colors, and the Winter is coming” – She said",
    "Crow didn't understand her. Why would she do that?",
    
    "“I have to go, see you soon” – she said as she flew away",
    "The next day, Crow flew away, again",
    "The curiosity about this robin was killing him",
    "Why does that robin like the colors so? Why are they so special?",
    "He flew over some prairies and found a beautiful blue flower",
    
    "He was not interested, but maybe with that he could get answers",
    "Heading back to the forest, he found her in the same branch…",
    "“Are you crazy? Do you want to die, again? – He asked",
    "“Oh, it’s you, always so happy” – she replied sarcastically",
    "“Here” – He said showing her the blue flower",
    
    "“Maybe with this you can forget about the pink flower” – He added",
    "“It’s beautiful!” – she said excited",
    "Crow was happy. He hadn´t felt such happiness in a long time ",
    
    "- Chapter 2 : About learning -",
    
    "For the following days, Crow was barely at the nest",
    "Every day early in the morning, he flew to the same forest…",
    "… where he found the same happy robin.",
    "Together they sought flowers of all colors.",
    "He didn't understand why yet, but he enjoyed the company",
    
    "“The autumn doesn´t seem as sad as before” – he thought",
    "He even quit thinking about staying during the winter",
    "“You can’t build nests with flowers” – he noted one day",
    "“I know, but the world will be sad without them” – She replied",
    "“It’s always sad for me anyway” – he said",
    
    "“I was born different to everyone, I hate it” – He explained",
    "the robin stared him, full of understanding",
    "“You’re special, you just don't realize it yet” – she said",
    "“That is easy for you to say” – He replied embarrassed",
    "“Or maybe you’re already in winter– She added",
    
    "“What do you mean?” – he asked",
    "“The winter takes the colors, all is cold and white there…",
    "… but the autumn is special. Do you know why? - she asked",
    "“Because of the colors?” – He tried to guess",
    "“No, because of the hope. The winter is inevitable…”",
    
    "“… but while you see all those colors in autumn…”",
    "“… there is hope that they will come back someday”",
    "That afternoon, while robin went back to her nest,",
    "Crow stayed thinking about what she had said earlier",
    "The follow days, he enjoyed her company even more ",
    
    "He felt that his way of life was starting to change ",
    "“What do you will do in the winter? – He asked one day",
    "“I don’t know, I don’t want go to south” – She replied",
    "“Why?” – He said – “You will die in the winter here”",
    "“There are still so many flowers to collect…",
    
    "… I want to believe that if I spread them during winter…",
    "… the colors will return and everything will be better”",
    "“That’s silly” – He sneered",
    "“I know, but dreaming is part of having hope” – she said",
    "Crow stared at her while she got ready to fly back to her nest",
    
    "“Hope can save you, sad Crow!” – She yelled from the distance",
    
    "- Chapter 3 : Resolutions-",
    
    "The next day, Crow left the nest early,",
    "he wanted to give something to robin, as gratitude",
    "He flew until the most distant prairie at the south,",
    "searched for hours, and finally he found it…",
    "the most beautiful pink flower he ever saw,",
    
    "similar to the one who Robin tried to reach so many times before",
    "Excited, he flew back to the forest, almost at sunset,",
    "saw her from the heights in the same branches,",
    "but, something was wrong, she wasn´t moving",
    "He came to her, and saw with sadness the scene",
    
    "A stray branch had pierced her body",
    "She didn’t sing cheerfully anymore…",
    "She was cold and quiet... She was gone forever.",
    "Devastated, Crow flew to where he guessed her nest was",
    "He felt a need to communícate to her family about her death",
    
    "“We know who she is, what a loss” – said another robin",
    "“Where is her family?” – he asked",
    "“Didn’t you know? She didn´t have one”– he explained ",
    "“Her parents died at beginning of the autum”",
    "While he flew back to his nest, he thought about everything",
    
    "“She was all alone, yet even then she had hope” – he thought",
    "“Hope can save you” – he remembered",
    "Suddenly, he knew what had to do",
    "Days later, everybody prepared themselves to fly south",
    "But Crow started to fly in the opposite direction",
    
    "He knew that was insane, but he had to try…",
    "…She had given him a reason to keep living",
    "That’s why, happy and full of hope…",
    "… he decided to collect every piece of color…",
    "… that autumn started to leave behind,",
    
    "And as such, he would face the terrible winter.",
    "He knew that his defeat was inevitable, but…",
    "“Dreaming is part of having hope” – he said to himself",
    "It is still said by those who know the story…",
    "… that to this day you can see in the snow the brave black bird…",
    
    "…fighting to find and put color in the winter,",
    "to keep the autumn song of his beloved robin alive...",
    "How long he could resist?...",
    
    "Do you need get a life bro!"  // Joke!
    
]

let conditionalsDictionary = [
    0:0,
    1:40,
    2:80,
    3:120,
    4:160,
    5:200,
    6:240,
    7:280,
    8:320,
    9:360,
    10:400,
    11:440,
    12:480,
    13:520,
    14:560,
    15:600,
    16:640,
    17:680,
    18:720,
    19:760,
    20:800,
    21:840,
    22:880,
    23:920,
    24:960,
    25:1000,
    26:1040,
    27:1080,
    28:1120,
    29:1160,
    30:1200,
    31:1240,
    32:1280,
    33:1320,
    34:1360,
    35:1400,
    36:1440,
    37:1480,
    38:1520,
    39:1560,
    40:1600,
    41:1640,
    42:1680,
    43:1720,
    44:1760,
    45:1800,
    46:1840,
    47:1880,
    48:1920,
    49:1960,
    50:2000,
    51:2040,
    52:2080,
    53:2120,
    54:2160,
    55:2200,
    56:2240,
    57:2280,
    58:2320,
    59:2360,
    60:2400,
    61:2440,
    62:2480,
    63:2520,
    64:2560,
    65:2600,
    66:2640,
    67:2680,
    68:2720,
    69:2760,
    70:2800,
    71:2840,
    72:2880,
    73:2920,
    74:2960,
    75:3000,
    76:3040,
    77:3080,
    78:3120,
    79:3160,
    80:3200,
    81:3240,
    82:3280,
    83:3320,
    84:3360,
    85:3400,
    86:3440,
    87:3480,
    88:3520,
    89:3560,
    90:3600,
    91:3640,
    92:3680,
    93:3720,
    94:3760,
    95:3800,
    96:3840,
    97:3880,
    98:3920,
    99:3960,
    100:4000,
    101:4040,
    102:4080,
    103:4120,
    104:4160,
    105:4200,
    106:4240,
    107:4280,
    108:4320,
    109:4360,
    110:4400,
    111:4440,
    112:4480,
    113:4520,
    114:4560,
    115:4600,
    116:4640,
    117:4680,
    118:4720,
    119:4760,
    120:4800,
    121:4840,
    122:4880,
    123:4920,
    
    124:99999,  // Joke!
    
]